spring:
  application:
    name: api-gateway
info:
  app:
    name: ${spring.application.name}
  #Gateway conf
  cloud:
    gateway:
      routes:
        - id: banking-service
          uri: lb://banking-service
          predicates:
            - Path=/banking-service/**
#--------------
server:
  port: 8888
#--------------
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
#--------------
