spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: banking-service
          uri: lb://banking-service
          predicates:
            - Path=/banking-service/**
          filters:
            - StripPrefix=1
        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/fund-transfer-service/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

info:
  app:
    name: ${spring.application.name}
  #Gateway conf
  #--------------
server:
  port: 8888
#--------------
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
#--------------