spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_user
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
server:
  port: 8989
app:
  config:
    keycloak:
      server-url: http://localhost:8080/
      realm: internet-banking-realm
      clientId: internet-banking-client-core
      client-secret: x80WqHMz4LswHEArFqiCrrFO8jbJUnW3