spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_user
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: javatodev-internet-banking
      clientId: internet-banking-api-client
      client-secret: e8548d56-d743-45ef-8655-063c9cd96759
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
server:
  port: 0