server:
  port: 8084
spring:
  application:
    name: internet-banking-fund-transfer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fund_transfer
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    name: ${spring.application.name}